networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

include:
  - compose/socket-proxy.yml
  - compose/traefik.yml
  # - compose/cloudflared.yml
  # - compose/portainer.yml
  # - compose/pihole.yml
