services:
  pihole:
    container_name: pihole
    image: "pihole/pihole:latest"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    volumes:
      - $DOCKERDIR/services/pihole/data:/etc/pihole/
      - $DOCKERDIR/services/pihole/dnsmasq.d/:/etc/dnsmasq.d/
    env_file: $DOCKERDIR/.env
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    networks:
      traefik_proxy:
        ipv4_address: 192.168.90.100
    labels:
      - "traefik.enable=true"
      # - "traefik.docker.network=docker_traefik_proxy"
      # HTTP Routers
      - "traefik.http.routers.pihole-rtr.rule=Host(`pihole.$DOMAINNAME_1`)"
      - "traefik.http.routers.pihole-rtr.entrypoints=websecure"
      # HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"
      # Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=middlewares-secure-headers@file"
      - "traefik.http.routers.pihole-rtr.middlewares=middlewares-rate-limit@file"